## THIS NOTEBOOK WILL NOT WORK IN GOOGLE COLAB!!! IT MUST BE RUN LOCALLY!!! You can download it as an .ipynb file and open that with Jupyter notebook/labs

In [1]:
!pip install pymysql
!pip install sqlalchemy

import sqlalchemy
import pymysql
from sqlalchemy import create_engine
import pandas as pd

Requirement already satisfied: pymysql in /Users/ellathomasson/anaconda3/lib/python3.11/site-packages (1.1.1)
Requirement already satisfied: sqlalchemy in /Users/ellathomasson/anaconda3/lib/python3.11/site-packages (1.4.39)

If you get an error saying something like "sqlalchemy not installed", you should add a code cell and write `pip install sqlalchemy`. Then, rerun the above cell (you might also need to install pymysql the same way)

In [2]:
password = 'Silverhorse$1'
db_name = 'songs'

In [3]:
conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password=password, database=db_name)

In [4]:
connection = create_engine("mysql+pymysql://root:" + password + "@localhost:3306/" + db_name)

In [42]:
song = pd.read_csv('/Users/ellathomasson/Downloads/Project 2 - Songs (2).csv')
artist = pd.read_csv('/Users/ellathomasson/Downloads/Project 2 - Artists.csv')
album = pd.read_csv('/Users/ellathomasson/Downloads/Project 2 - Albums.csv')
playlist = pd.read_csv('/Users/ellathomasson/Downloads/Project 2 - Playlists.csv')
user = pd.read_csv('/Users/ellathomasson/Downloads/Project 2 - Users (1).csv')

59

In [43]:
table_name1 = 'Song'
table_name2 = 'Artists'
table_name3 = 'Albums'
table_name4 = 'Playlists'
table_name5 = 'Users'

In [44]:
song.to_sql(name=table_name1, con=connection, if_exists='replace', index=False)
artist.to_sql(name=table_name2, con=connection, if_exists='replace', index=False)
album.to_sql(name=table_name3, con=connection, if_exists='replace', index=False)
playlist.to_sql(name=table_name4, con=connection, if_exists='replace', index=False)
user.to_sql(name=table_name5, con=connection, if_exists='replace', index=False)

10

We use SQL syntax for querying. The triple quotation mark syntax allows us to write commands simiar to how we did in SQL

In [45]:
query1 = "SELECT * FROM songs"
query2 = """

SELECT * FROM facts
WHERE Title ='Happier'

"""

In [46]:
result_df = pd.read_sql(query1, con=connection)

In [47]:
result_df

,Song_ID,Title,Artist_ID,Album_ID,Playlist_ID,Genre,Rating,Duration
0,1,Happier,1.0,1.0,1.0,Pop,7,4:16
1,2,Enough for You,1.0,1.0,4.0,Pop,6,2:47
2,3,Deja Vu,1.0,1.0,7.0,Pop,10,4:01
3,4,Brutal,1.0,1.0,10.0,Pop,5,3:18
4,5,Kiss Me More,9.0,7.0,5.0,Pop,8,3:12
5,6,American Idiot,3.0,8.0,8.0,Rock,7,3:24
6,7,Boulevard of Broken Dreams,3.0,8.0,10.0,Rock,8,4:45
7,8,Homecoming,3.0,8.0,9.0,Rock,6,8:46
8,9,Golden,8.0,2.0,1.0,Pop,7,3:50
9,10,Adore You,8.0,2.0,5.0,Pop,7,4:25
10,11,Love to Dream,9.0,7.0,1.0,Pop,6,2:23
11,12,When We Were Young,NaN,NaN,4.0,Pop,10,4:30
12,13,I Knew You Were Trouble,7.0,3.0,9.0,Pop,10,4:06
13,14,All Too Well,7.0,3.0,5.0,Pop,9,10:21
14,15,State of Grace,7.0,3.0,8.0,Pop,7,3:34
15,16,Two-Headed Boy,2.0,9.0,3.0,Indie,4,4:23
16,17,White Horse,7.0,NaN,2.0,Pop,5,4:25
17,18,Baby for Pree,2.0,NaN,4.0,Indie,3,2:33
18,19,Vampire,1.0,NaN,3.0,Pop,10,3:53
19,20,Yeh Kya Hua,11.0,NaN,10.0,Bollywood,9,3:23
20,21,Yellow,5.0,6.0,1.0,Rock,9,4:29
21,22,Shiver,5.0,6.0,NaN,Rock,8,4:59
22,23,Sparks,5.0,6.0,NaN,Rock,8,3:47
23,24,Trouble,5.0,6.0,NaN,Rock,9,4:30
24,25,Don't Panic,5.0,6.0,7.0,Alternative Rock,8,2:17
25,26,All I Want,4.0,4.0,NaN,Indie,8,5:05
26,27,High Hopes,4.0,4.0,2.0,Indie,8,3:51
27,28,Love Like This,4.0,4.0,3.0,Indie,7,3:38
28,29,All Comes Down,4.0,4.0,3.0,Indie,7,4:01
29,30,Talk,4.0,4.0,4.0,Indie,7,4:22
30,31,Hardwired,6.0,5.0,NaN,Pop,7,3:36
31,32,Loopty Loop,6.0,5.0,NaN,Pop,8,3:29
32,33,Awkward,6.0,5.0,NaN,Pop,7,3:25
33,34,My Worst Enemy,6.0,5.0,NaN,Pop,7,3:08
34,35,Geeks,6.0,5.0,NaN,Pop,8,2:55
35,36,Watermelon Sugar,8.0,2.0,2.0,Pop,9,2:54
36,37,Sign of the Times,8.0,2.0,4.0,Rock,9,5:40
37,38,Adore You (Live),8.0,2.0,3.0,Pop,8,3:27
38,39,Falling,8.0,2.0,7.0,Pop,8,4:00
39,40,Golden (Live),8.0,2.0,1.0,Pop,8,3:28
40,41,Love Story,7.0,3.0,5.0,Pop,9,3:55
41,42,Blank Space,7.0,NaN,8.0,Pop,9,3:51
42,43,Shake It Off,7.0,NaN,2.0,Pop,8,3:39
43,44,Cardigan,7.0,NaN,9.0,Indie,8,4:00
44,45,Willow,7.0,NaN,10.0,Indie,8,3:34
45,46,Blinding Lights,NaN,NaN,4.0,Pop,9,3:20
46,47,Levitating,NaN,NaN,2.0,Pop,8,3:23
47,48,Too Sweet,14.0,10.0,NaN,Indie,7,4:11
48,49,Take Me to Church,14.0,10.0,NaN,Indie,10,4:01
49,50,Work Song,14.0,10.0,NaN,Indie,6,3:49
50,51,Almost,14.0,10.0,NaN,Indie,6,3:37
51,52,rEaL WOrLD,15.0,11.0,NaN,Pop,8,2:58
52,53,Solamente,15.0,11.0,NaN,Pop,7,2:14
53,54,Stuck In The Middle,15.0,11.0,NaN,Pop,9,3:16
54,55,AOK,15.0,11.0,NaN,Pop,8,2:53
55,56,Violet,16.0,12.0,NaN,Pop,7,2:02
56,57,Spinnin,16.0,12.0,NaN,Pop,9,1:50
57,58,Drop,16.0,12.0,NaN,Pop,6,2:08
58,59,False Alarm,16.0,12.0,NaN,Pop,7,2:22

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'songs.facts' doesn't exist")
[SQL:

SELECT * FROM facts
WHERE Title ='Happier'

]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [ ]:
result_df_2

We can merge in PyMySQL just like in regular SQL

In [ ]:
df2 = pd.DataFrame({'_id':[1,2,3] , 'Is_Primary':[False,True,False], 'Hex_Code':['#A020F0', '#0000FF', '#00FF00']})
df2

In [ ]:
df2.to_sql(name='color_table', con=connection, if_exists='replace', index=False)

In [ ]:
query3 = """
  SELECT facts.Names, facts.Favorite_Color, color_table.Is_Primary, color_table.Hex_Code
  FROM facts
  LEFT JOIN color_table ON facts.Favorite_Color = color_table.Colors
"""

In [ ]:
result_df_3 = pd.read_sql(query3, con=connection)

In [ ]:
result_df_3